name: "LightNode"

lights:
  - name: "Left Bulb"
    driver: "LB130"
    ip: "192.168.1.200"
    port: 9999
  
  - name: "Right Bulb"
    driver: "LB130"
    ip: "192.168.1.201"
    port: 9999
  
  - name: "Matrix"
    driver: "APA102"
    size: 768
